version: "3"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./data/sq/conf:/opt/sonarqube/conf
      - ./data/sq/data:/opt/sonarqube/data
      - ./data/sq/extensions:/opt/sonarqube/extensions
      - ./data/sq/logs:/opt/sonarqube/logs

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./data/sq/:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./data/pg/data:/var/lib/postgresql/data

networks:
  sonarnet:
